### ISSUE TITLE
封面图错误

### ISSUE THREAD

**Issue by githubwing** [ProgramLeague/PLASTIC_RPG#2]
怎么出来个toolbar 吓尿

**Comment by ice1000** [comment]
蛤？你下载了可执行文件吗。。。

**Comment by ice1000** [comment]
哦，那个就是正式的封面图，我随手截了张代码的图直接贴上去的

**Comment by githubwing** [comment]
没。。我是mac。。我就是随便逛了逛这里

**Comment by ice1000** [comment]
哦。。。好吧。很遗憾。那么求围观[这个游戏引擎，是一个系列](https://github.com/icela/FriceEngine)，还有C#版 Racket版 Android版
